---
- name: Ensure Nextcloud HTML volume directory exists
  ansible.builtin.file:
    path: ./srv/nextcloud/html
    state: directory
    owner: 33     # UID of www-data in the container
    group: 33
    mode: '0755'

- name: Create Nextcloud container
  community.docker.docker_container:
    name: nextcloud
    image: nextcloud:latest
    state: started
    restart_policy: always
    ports:
      - "8080:80"
    networks:
      - name: nextcloud_network
    env:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: "{{ vault_postgres_password }}"
      POSTGRES_HOST: nextcloud_db
    volumes:
      - /srv/nextcloud/html:/var/www/html
