---
- name: Ensure Postgres data directory exists
  ansible.builtin.file:
    path: /mnt/storage/postgres
    state: directory
    owner: 999   # default UID for postgres in official image
    group: 999
    mode: '0700'

- name: Ensure PostgreSQL container is running
  docker_container:
    name: nextcloud_db
    image: postgres:15
    state: started
    restart_policy: always
    networks:
      - name: nextcloud_network
    ports:
      - "5432:5432"
    env:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: "{{ vault_postgres_password }}"
    volumes:
      - /mnt/storage/postgres:/var/lib/postgresql/data
  become: yes

- name: Wait for PostgreSQL to be ready
  wait_for:
    host: localhost
    port: 5432
    delay: 5
    timeout: 60
